[project]
name = "sitegen"
version = "0.1.0"
description = "Simple static site generation used for my personal site"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "pygments>=2.19.2",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
]

[project.scripts]
sitegen = "sitegen.__main__:main"

[tool.uv]
package = true

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "--cov --cov-report term-missing"

